import { styled, Theme, Typography } from "@mui/material";
import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { SiteNav, CenteredPage } from "../components";

const GradientText = styled(Typography)(({ theme }: { theme: Theme }) => ({
  fontSize: "148px",
  fontWeight: "bold",
  background: `-webkit-linear-gradient(217deg, #9198e5, ${theme.palette.primary.main})`,
  "-webkit-background-clip": "text",
  "-webkit-text-fill-color": "transparent",
}));

const Home: NextPage = () => {
  const { data: session, status } = useSession();
  return (
    <div>
      <Head>
        <title>Pollz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SiteNav authed={Boolean(session)} />
        <CenteredPage>
          <GradientText variant="h1">POLLZ</GradientText>
        </CenteredPage>
      </main>
    </div>
  );
};

export default Home;
