import { useEffect } from "react";
import { signIn, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import { Button, CircularProgress } from "@mui/material";
import { NextPage } from "next";
import { CenteredPage, SiteNav } from "../components";
import Head from "next/head";
import GitHubIcon from "@mui/icons-material/GitHub";

const Login: NextPage = () => {
  const { data: session, status } = useSession();
  const router = useRouter();

  useEffect(() => {
    console.log("session: ", session);
    console.log("status: ", status);
    if (session) {
      router.push("/dashboard");
    }
  }, [session, status, router]);

  return (
    <div>
      <Head>
        <title>Pollz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SiteNav authed={Boolean(session)} />
        <CenteredPage>
          {status === "loading" && <CircularProgress />}
          {status !== "loading" && (
            <Button variant="outlined" onClick={() => signIn("github")}>
              <GitHubIcon sx={{ marginRight: "15px" }} />
              {"Log In With GitHub"}
            </Button>
          )}
        </CenteredPage>
      </main>
    </div>
  );
};

export default Login;
